### ISSUE TITLE
Combobox - selectionDisplay missing "selected" string in chip

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10896]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

On the `dev` branch the chip shows `2`
![CleanShot 2024-11-26 at 17 29 01@2x](https://github.com/user-attachments/assets/d05345ec-d8f2-499d-b530-e41847aab481)

### Expected Behavior

On v2.13.2 the chips shows `2 selected`
![CleanShot 2024-11-26 at 17 31 12@2x](https://github.com/user-attachments/assets/316c7cc8-98bb-406d-9980-0ad6a3ac25fd)

### Reproduction Sample

https://esri.github.io/calcite-design-system/?path=/story/components-controls-combobox--multiple

### Reproduction Steps

Scroll down to the selection-display="single" group

### Reproduction Version

v3.0-next

### Relevant Info

cc @jcfranco 

### Regression?

v2.13.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
@ashetland This seems to have been resolved. I'm seeing the selected text locally as well as on the repro link. Could you take a look and confirm that it's working as expected now.

**Comment by ashetland** [comment]
I'm still seeing the missing text here https://esri.github.io/calcite-design-system/?path=/story/components-controls-combobox--multiple

**Comment by ashetland** [comment]
I think this is based on my viewport. When I go wider, I see everything as expected. Closing this issue.

**Comment by DitwanP** [comment]
@ashetland I thought the compact indicator chip meant that it wouldn't have the 'selected' text.
