### ISSUE TITLE
[Dropdown] Add support for dedicated context menu leveraging popover reference element

### ISSUE THREAD

**Issue by nick-romano** [Esri/calcite-design-system#12426]
**monday.com sync:** #9984894121

### Description

Blocked by: #13961, #8206

Couldn't find a duplicate, but apologies if I missed it and this has already been requested!

It would be really nice to have a dedicated context menu component. Something like this one from Radix: https://www.radix-ui.com/primitives/docs/components/context-menu

This component would mimic the right click menu on modern desktop operating systems or the "long press" menu on mobile operating systems.

### User Stories

A right-click (context menu) in a web application adds a layer of contextual interaction, allowing users to quickly access actions relevant to the specific element or area they are interacting with. This can improve efficiency, discoverability, and user experience, especially for power users.

Benefits:

- Contextual Actions: Shows only the actions that make sense for the selected item or area, reducing clutter in the main UI.
- Efficiency: Enables faster workflows by reducing the number of clicks or navigation steps needed to perform common tasks.
- Familiarity: Mimics desktop application behavior, making web apps feel more powerful and intuitive for users accustomed to right-click menus.

User stories:

- Data Grids/Tables: Right-click a row or cell to access actions like Edit, Copy, Export, or Filter.
- File Management: Right-click on a file or folder to show options like Rename, Delete, Download, Move, or Share.
- Maps & GIS: Right-click on a map to drop a pin, get coordinates, measure distance, or add a marker.

My use case falls in the Data Grids / Tables category. Allowing users to select specific keys in a calcite-tree.

### Acceptance Criteria

- [ ] Dropdown supports a `referenceElement` property that takes precedence over the `trigger` slot
- [ ] JSDoc encourages use of `referenceElement` and communicates its precedence

### Priority impact

impact - p3 - not time sensitive

### Esri team

ArcGIS Maps SDK for JavaScript

### Archived Acceptance Criteria

> 1. **Triggering**
>    - The context menu can be opened via right-click (mouse secondary button) on desktop.
>    - The context menu can be opened via long-press on touch devices.
> 
> 2. **Menu Content**
>    - Developers can define a list of menu items, including text, icons, and separators.
>    - Supports nested submenus.
>    - Supports disabled and hidden menu items.
> 
> 3. **Accessibility**
>    - The menu is fully keyboard accessible (open with keyboard, navigate with arrow keys, select with Enter/Space, close with Escape).
>    - Proper ARIA roles and attributes are applied for screen readers.
>    - Focus is managed correctly when the menu opens and closes.
> 
> 4. **Positioning**
>    - The menu appears at the cursor location or touch point.
>    - Page scrolling is blocked when the menu is opened?
> 
> 5. **Event Handling**
>    - Selecting a menu item triggers an event.
>    - The menu closes when clicking outside, pressing Escape, or selecting an item.
> 
> 6. **Styling & Theming**
>    - The menu and items can be styled via CSS variables.
> 
> 7. **Integration**
>    - The component works with a "reference-element" similar to popover and tooltip?
> 
> 8. **Performance**
>    - The menu renders efficiently, even with many items or nested submenus.
>    - No memory leaks or lingering event listeners after unmount.

**Comment by macandcheese** [comment]
I wonder if this is a good candidate for a map component. It seems like our existing components like Menu, Dropdown, Popover, etc. (and related open enhancements) could all be used or configured to achieve this behavior. 

The right click seems to be the unique UX here. Could this be handled in a shared component in a library that consumes Calcite, rather than in Calcite itself?

**Comment by nick-romano** [comment]
> I wonder if this is a good candidate for a ~~map~~ common component. It seems like our existing components like Menu, Dropdown, Popover, etc. (and related open enhancements) could all be used or configured to achieve this behavior.
> 
> The right click seems to be the unique UX here. Could this be handled in a shared component in a library that consumes Calcite, rather than in Calcite itself?

It's possible, but would be a bit difficult with menu, which feels like the current default choice based on the palette of components. 

Menu feels like it's usage is targeted for page navigation:
![Image](https://github.com/user-attachments/assets/5c951449-90bf-4fa4-9c7a-78bf53c95245)

It would need some scaling options to start...

Dropdown looks better visually, but doesn't support submenus.

So yeah, it would be difficult without changes to menu...

**Comment by ashetland** [comment]
Related issues:

- Menu scales: https://github.com/Esri/calcite-design-system/issues/12337
- Menu submenus: https://github.com/Esri/calcite-design-system/issues/9965
- Dropdown submenus: https://github.com/Esri/calcite-design-system/issues/9745

Nothing official on those issues just yet, but we'll be looking into them this month.

**Comment by driskull** [comment]
@jcfranco @geospatialem since this would require a breaking change can we move this into a breaking change milestone? Preferably something for R1 since this issue is blocking development for the contextual menu arcgis component.

**Comment by geospatialem** [comment]
Adding the `spike` label to determine if we can add new functionality with the above, in addition to the component's `"trigger"` slot, which would be deprecated as a result. If the support is possible for both the new functionality, and the current setup of the `"trigger"` slot we should consider the change prior to 26.R1, otherwise this could be a `breaking change` for the next major release.

**Comment by driskull** [comment]
I prototyped this a bit and it does seem to be possible to have both the slotted trigger and the referenceElement property as long as we decide which one takes priority over the other. I would assume the newer referenceElement would win in this scenario.

@geospatialem we can proceed with this

**Comment by driskull** [comment]
One question is do we have built in support for right-click and long press or do we just allow users to set the positioning using a virtual reference element (screen position). My guess would be built in support for right-click, long press as the virtual element isn't very user friendly. https://floating-ui.com/docs/virtual-elements

**Comment by ashetland** [comment]
> My guess would be built in support for right-click, long press

Agreed.

**Comment by driskull** [comment]
Cool, so we'd probably just add a value of `"right-click"` or `"context"` to the existing dropdown `type` property and it would handle right-click and long press.

**Comment by driskull** [comment]
@geospatialem can we unspike this and move it to a milestone for R1? Maybe the Jan/Feb one?

**Comment by macandcheese** [comment]
"context" is nice because invoking a UX like the ones described here isn't always done with right click. It could be control + click, etc. Though there are likely other components that could be invoked from those controls.

**Comment by driskull** [comment]
@jcfranco @macandcheese @geospatialem I'm thinking if we want to get the context menu working first, we should break this issue into two.

1. Add context type to dropdown
2. Add referenceElement property to dropdown

The referenceElement work is a lot bigger and requires some refactoring to the existing PopoverManager/TooltipManager to make them more universal and reuse some code. They could become something like ClickManager/HoverManager and share code with dropdown.

Thoughts?

**Comment by driskull** [comment]
@geospatialem @isaacbraun can I get a new issue to create a `useReferenceElement` controller that will handle logic for popover, tooltip and dropdown? This will help unify and allow any future components to adopt the `referenceElement` logic. Once this is complete, I can add logic for handling context menu to the new controller.

As part of this work, I can also handle #13242

**Comment by isaacbraun** [comment]
> [@geospatialem](https://github.com/geospatialem) [@isaacbraun](https://github.com/isaacbraun) can I get a new issue to create a `useReferenceElement` controller that will handle logic for popover, tooltip and dropdown?

Done! ✅ Triaged and placed in the current milestone, as well as marked it as blocking this and #13242. Feel free to adjust the description if I got something incorrect 👍

**Comment by macandcheese** [comment]
From a design system component perspective I still don’t think this is the correct approach. A context menu UX may be comprised of any component. Not just a dropdown. It could be a popover containing a List for example. 

The ask makes sense, but I believe just having an example of invoking an element (any element) with a right click is a better, more holistic solution, rather than just a mode of Dropdown, which is very limiting.

**Comment by isaacbraun** [comment]
After discussion, we'll be moving forward with the following:
- Supporting `referenceElement` on Dropdown, with it taking precedence over the `trigger` slot
- Deprecating the `trigger` slot, with a slower removal likely planned for 2027.R1 - #14173 
- Once released, provide a sample for how to implement a context menu with both context (`right-click`) and long-press for mobile using a virtual element

**Comment by driskull** [comment]
@DitwanP @isaacbraun the deprecation doc for this will need to be adjusted

**Comment by isaacbraun** [comment]
Verified on `5.1.0-next.31` via https://codepen.io/isaacbraun/pen/bNwXVOp and the doc site that:
- Dropdown supports a `referenceElement` property
- The `trigger` slot still functions as expected
- When both a `referenceElement` and `trigger` are provided, the `referenceElement` takes precedent and the `trigger` is not rendered.
- JSDoc encourages use of `referenceElement` and states that the `trigger` element is deprecated.
	- It **does not** specifically call out that `trigger` will not render if a `referenceElement` is provided. cc @Esri/calcite-pes I think this is okay since `trigger` is deprecated, but waiting to close until others confirm/disagree.

<img width="1015" height="135" alt="Image" src="https://github.com/user-attachments/assets/7c78f765-6167-436d-bf2f-9e1dc1ab30a7" />

**Comment by DintaMel** [comment]
> It does not specifically call out that trigger will not render if a referenceElement is provided. cc @Esri/calcite-pes I think this is okay since trigger is deprecated, but waiting to close until others confirm/disagree.

That seems okay to me.
