### ISSUE TITLE
calcite-select: Allow having no initial value

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-design-system#4032]
### Description

It is sometimes useful to have no initial value for a `select` to coerce the user to make an explicit decision. Currently this seems to not be supported by `calcite-select` since it seems to always be initialized with the first `calcite-option` child's value if `value` is undefined and no `calcite-option` is `selected`. In plain HTML, `<option hidden disabled />` might be used, however doing `<calcite-option hidden disabled />` still causes it to be visible in the menu.

### Acceptance Criteria

- [ ] When no `value` is set, and no `calcite-option` is selected, the `calcite-select` renders its placeholder and does not initialize itself with a default value

### Which Component

calcite-select

### Example

https://codepen.io/arjan_esrinl/pen/ZEmgaVv

**Comment by macandcheese** [comment]
This one's tough as we match native behavior and there is no native placeholder attribute.

The single-select combobox could accomplish this:

```
<calcite-combobox placeholder="Select a value" selection-mode="single">
    <calcite-combobox-item value="Engineering" text-label="Engineering"></calcite-combobox-item>
    <calcite-combobox-item value="Architecture" text-label="Architecture"></calcite-combobox-item>
    <calcite-combobox-item value="Construction" text-label="Construction"></calcite-combobox-item>
</calcite-combobox>
```

Although the above [does not allow you to clear selection](https://github.com/Esri/calcite-components/issues/3074) - not sure if that is desirable for your workflow.

**Comment by jgibson02** [comment]
@macandcheese what're your thoughts on supporting `hidden` on a `calcite-option` to hide it from the list and act like a placeholder akin to the native behavior?

**Comment by macandcheese** [comment]
That would work - it seems like that works only when `hidden` is the first option. Maybe we could just render that internally based on the presence of an (added) placeholder attribute? Would be open to either option there.

**Comment by jgibson02** [comment]
If it only works for the first option, then your suggestion certainly sounds cleaner to me rather than adding a `hidden` prop and depending on documenting that behavior.

**Comment by ReneU** [comment]
+1 We need this to allow having no initial value for some components in ArcGIS Velocity. We have some required fields that don't allow for good defaults such as this one:
![image](https://user-images.githubusercontent.com/5748802/176642918-c15ebd63-8777-4f10-8138-bb9b5a17d5b9.png)

**Comment by ReneU** [comment]
@macandcheese @jcfranco @benelan are there any plans to support this in one of the upcoming releases? We have a lot of UIs in ArcGIS Velocity we would like to migrate but this is the only issue blocking us from doing so since we don't want to have a mixed experience (UI controls from different component libraries on the same page).

**Comment by jcfranco** [comment]
Would using an 'empty' option work in the meantime? https://codepen.io/jcfranco/pen/oNqMBRJ?editors=1010

> it seems to always be initialized with the first calcite-option child's value if value is undefined

Assuming ☝️ was fixed, would this address this issue or are there additional functional differences from the MDN example? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#try_it

**Comment by ReneU** [comment]
@jcfranco yes, I think we could go with the 'empty' option for now. Thank you.

It seems like it's still getting initialized with the first `calcite-option` child's value if `value` is undefined. However, it looks like this matches the native behavior. I guess that's not a blocker for us and we could implement a workaround.

The only remaining thing that would be great to have (and is a [functional difference](https://codepen.io/reneu/pen/RwMBxVN)) is the `hidden` prop, as discussed above.

**Comment by geospatialem** [comment]
- An example where the innerText is used where the `value` is `""`: https://codepen.io/arjan_esrinl/pen/ZEmgaVv
- And a workaround with normalization: https://codepen.io/jcfranco/pen/oNQKdEg

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.5`.
